In [193]:
# Import the required libraries and dependencies
import os
import requests
import json
import pandas as pd
from dotenv import load_dotenv
from pycoingecko import CoinGeckoAPI
from datetime import datetime
from defillama import DefiLlama


%matplotlib inline

In [194]:
# The Coingecko endpoint URLs for the held cryptocurrency assets
aave_url = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=aave"
compound_url = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=compound-governance-token"
cg = CoinGeckoAPI()

# initialize api client
llama = DefiLlama()

# Get all protocols data
response_llama = llama.get_all_protocols()
print(json.dumps(response_llama[0], indent=4, sort_keys=True))

{
    "address": "0xD533a949740bb3306d119CC777fa900bA034cd52",
    "audit_links": [
        "https://curve.fi/audits"
    ],
    "audit_note": null,
    "audits": "2",
    "category": "Dexes",
    "chain": "Multi-Chain",
    "chainTvls": {
        "Arbitrum": 245067633.9184719,
        "Avalanche": 1228408896.3892138,
        "Ethereum": 15915698647.873163,
        "Ethereum-staking": 1025987115.8480968,
        "Fantom": 668412433.7580248,
        "Harmony": 35680974.476177506,
        "Optimism": 335478.22218436166,
        "Polygon": 382729770.1826564,
        "staking": 1025987115.8480968,
        "xDai": 92448600.57374793
    },
    "chains": [
        "Ethereum",
        "Avalanche",
        "Fantom",
        "Polygon",
        "Arbitrum",
        "xDai",
        "Harmony",
        "Optimism"
    ],
    "change_1d": -2.3577030748913756,
    "change_1h": -0.00014569441795231342,
    "change_7d": -5.809534857988936,
    "cmcId": "6538",
    "description": "Curve is a decentralized exchange liquidity pool on Ethereum designed for extremely efficient stablecoin trading",
    "fdv": 7698842085,
    "gecko_id": "curve-dao-token",
    "id": "3",
    "language": "Vyper",
    "logo": "https://icons.llama.fi/curve.png",
    "mcap": 913592440,
    "module": "curve/index.js",
    "name": "Curve",
    "oracles": [],
    "slug": "curve",
    "staking": 1025987115.8480968,
    "symbol": "CRV",
    "tvl": 18568908068.558487,
    "twitter": "CurveFinance",
    "url": "https://curve.fi"
}

In [195]:


# Get a protocol data for uniswap
uniswap_response = llama.get_protocol(name='uniswap')

# Get all TVL from Ethereum network, not other networks
uniswap_response_df = pd.DataFrame(uniswap_response['chainTvls']['Ethereum']['tvl'], columns=['date','totalLiquidityUSD'])



uniswap_response_df['date'] = pd.to_datetime(uniswap_response_df['date'],unit='s')
uniswap_response_df.set_index('date',inplace=True)
uniswap_response_df.head()
# print(json.dumps(uniswap_response, indent=4, sort_keys=True))

            totalLiquidityUSD
date
2018-11-03       34684.037747
2018-11-04       41292.993049
2018-11-05       41550.309965
2018-11-06       43233.560074
2018-11-07      153862.566498

In [196]:
uniswap_response_df.describe()

       totalLiquidityUSD
count       1.181000e+03
mean        2.638968e+09
std         3.367927e+09
min         3.468404e+04
25%         1.820555e+07
50%         7.820865e+07
75%         5.883141e+09
max         1.039974e+10

In [197]:

llama_df = pd.DataFrame(response_llama, columns=['name','symbol','chains','mcap','tvl'])
llama_df = llama_df.rename(columns={'mcap':'Market Cap','tvl':'Total Value Locked','chains':'Network'})

llama_df['MCAP/TVL'] = llama_df['Market Cap']/llama_df['Total Value Locked']

llama_df.head()
# print(json.dumps(response_llama, indent=4, sort_keys=True))

,name,symbol,Network,Market Cap,Total Value Locked,MCAP/TVL
0,Curve,CRV,"[Ethereum, Avalanche, Fantom, Polygon, Arbitru...",9.135924e+08,1.856891e+10,0.049200
1,MakerDAO,MKR,[Ethereum],1.526796e+09,1.549071e+10,0.098562
2,Convex Finance,CVX,[Ethereum],1.072885e+09,1.268626e+10,0.084571
3,AAVE,AAVE,"[Ethereum, Avalanche, Polygon]",1.796088e+09,1.152387e+10,0.155858
4,Polygon Bridge & Staking,MATIC,[Polygon],9.707403e+09,1.034399e+10,0.938458

In [235]:
# Get a protocol data
aave_response = llama.get_protocol(name='aave')

# Get a protocol data
compound_response = llama.get_protocol(name='compound')

# Get a protocol data
curve_response = llama.get_protocol(name='curve')

# Get a protocol data
uniswap_response = llama.get_protocol(name='uniswap')

# Get a protocol data
makerdao_response = llama.get_protocol(name='makerdao')

aave_defi_df = pd.DataFrame(
    aave_response['tvl'], 
    columns=['date', 
    'totalLiquidityUSD']).rename(columns={'totalLiquidityUSD':'AAVE TVL'}
                                                                        )

compound_defi_df = pd.DataFrame(
    compound_response['tvl'],
    columns=['date', 
    'totalLiquidityUSD']).rename(columns={'totalLiquidityUSD':'COMP TVL'}
                                )
curve_defi_df = pd.DataFrame(
    curve_response['tvl'], 
    columns=['date', 
    'totalLiquidityUSD']).rename(columns={'totalLiquidityUSD':'CURVE TVL'})

uniswap_defi_df = pd.DataFrame(uniswap_response['tvl'], 
    columns=['date', 
    'totalLiquidityUSD']).rename(columns={'totalLiquidityUSD':'UNISWAP TVL'})

makerdao_defi_df = pd.DataFrame(
    makerdao_response['tvl'], 
    columns=['date', 
    'totalLiquidityUSD']).rename(columns={'totalLiquidityUSD':'MAKER DAO TVL'})

aave_defi_df['date'] = pd.to_datetime(aave_defi_df['date'], unit='s')
compound_defi_df['date'] = pd.to_datetime(compound_defi_df['date'], unit='s')
curve_defi_df['date'] = pd.to_datetime(curve_defi_df['date'], unit='s')
uniswap_defi_df['date'] = pd.to_datetime(uniswap_defi_df['date'], unit='s')
makerdao_defi_df['date'] = pd.to_datetime(makerdao_defi_df['date'], unit='s')

#set the index column for each dataframe to 'date'
aave_defi_df.set_index('date',inplace=True)
compound_defi_df.set_index('date',inplace=True)
curve_defi_df.set_index('date',inplace=True)
uniswap_defi_df.set_index('date',inplace=True)
makerdao_defi_df.set_index('date',inplace=True)

# combine_defi_df = [aave_defi_df, compound_defi_df, curve_defi_df, uniswap_defi_df, 
#wbtc_defi_df, makerdao_defi_df]

aave_defi_df = aave_defi_df.dropna()
compound_defi_df = compound_defi_df.dropna()
curve_defi_df = curve_defi_df.dropna()
uniswap_defi_df = uniswap_defi_df.dropna()
makerdao_defi_df = makerdao_defi_df.dropna()


tvl_df = pd.concat([aave_defi_df, 
                    compound_defi_df, 
                    curve_defi_df, 
                    uniswap_defi_df, 
                    makerdao_defi_df]).groupby(['date']).sum()
#tvl_df.fillna(method= 'pad')
tvl_df=tvl_df.mask(tvl_df==0).ffill(downcast='infer').fillna(0)

tvl_df.info()
display(tvl_df.head(100))
display(tvl_df.tail(10))

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2147 entries, 2018-11-03 00:00:00 to 2022-02-22 11:14:28
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AAVE TVL       2147 non-null   float64
 1   COMP TVL       2147 non-null   float64
 2   CURVE TVL      2147 non-null   float64
 3   UNISWAP TVL    2147 non-null   float64
 4   MAKER DAO TVL  2147 non-null   float64
dtypes: float64(5)
memory usage: 100.6 KB

            AAVE TVL  COMP TVL  CURVE TVL   UNISWAP TVL  MAKER DAO TVL
date
2018-11-03       0.0       0.0        0.0  3.468404e+04   0.000000e+00
2018-11-04       0.0       0.0        0.0  4.129299e+04   0.000000e+00
2018-11-05       0.0       0.0        0.0  4.155031e+04   0.000000e+00
2018-11-06       0.0       0.0        0.0  4.323356e+04   0.000000e+00
2018-11-07       0.0       0.0        0.0  1.538626e+05   0.000000e+00
...              ...       ...        ...           ...            ...
2019-02-06       0.0       0.0        0.0  7.902150e+05   2.185224e+08
2019-02-07       0.0       0.0        0.0  8.485165e+05   2.109902e+08
2019-02-08       0.0       0.0        0.0  9.922616e+05   2.161253e+08
2019-02-09       0.0       0.0        0.0  1.208893e+06   2.208961e+08
2019-02-10       0.0       0.0        0.0  1.296437e+06   2.465161e+08

[100 rows x 5 columns]

,AAVE TVL,COMP TVL,CURVE TVL,UNISWAP TVL,MAKER DAO TVL
date,,,,,
2022-02-15 00:00:00,1.326397e+10,7.054297e+09,1.943360e+10,7.358130e+09,1.696476e+10
2022-02-16 00:00:00,1.377203e+10,7.543162e+09,1.987663e+10,7.783955e+09,1.790344e+10
2022-02-17 00:00:00,1.357224e+10,7.504268e+09,1.986333e+10,7.836969e+09,1.768059e+10
2022-02-18 00:00:00,1.274358e+10,6.898350e+09,1.948774e+10,7.836969e+09,1.665379e+10
2022-02-18 10:02:37,1.274358e+10,6.898350e+09,1.948774e+10,7.525129e+09,1.665379e+10
2022-02-19 00:00:00,1.247254e+10,6.754811e+09,1.927637e+10,7.525129e+09,1.634400e+10
2022-02-20 00:00:00,1.242510e+10,6.713230e+09,1.924455e+10,7.525129e+09,1.638663e+10
2022-02-21 00:00:00,1.203861e+10,6.601931e+09,1.890430e+10,7.525129e+09,1.594744e+10
2022-02-22 11:02:41,1.159063e+10,6.481427e+09,1.863420e+10,7.525129e+09,1.594744e+10
2022-02-22 11:14:28,1.159063e+10,6.481427e+09,1.863420e+10,7.525129e+09,1.566187e+10

In [199]:
# Navigate the AAVE response object to access the current price of AAVE
aave_price = aave_response[0]['current_price']

# Print the current price of AAVE
print(f'The current price of AAVE is ${aave_price}.')
aave_df = pd.DataFrame(aave_response, columns=['ath_date','current_price','market_cap','max_supply','total_volume'])
aave_df.set_index('ath_date',inplace=True)
aave_df

KeyError: 0

In [15]:

# Get AAVE price directly from CoinGecko using CoinGeckoAPI()
# Note that the price is different from getting the price using response object
aave_price_cg = cg.get_price(ids='aave', vs_currencies='usd')
aave_price_cg = aave_price_cg['aave']['usd']
print(f'The current price of AAVE is ${aave_price_cg}.')

The current price of AAVE is $129.41.

In [16]:
print(json.dumps(compound_response, indent=4, sort_keys=True))

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [17]:
# Navigate the Compound response object to access the current price of Compound
compound_price = compound_response[0]['current_price']

# Print the current price of COMP
print(f'The current price of COMP is ${compound_price}.')

KeyError: 0

In [18]:
# Get COMP price directly from CoinGecko using CoinGeckoAPI()
# Note that the price is different from getting the price using response object
compound_price_cg = cg.get_price(ids='compound-governance-token', vs_currencies='usd')
compound_price_cg = compound_price_cg['compound-governance-token']['usd']

print(f'The current price of COMP is ${compound_price_cg}.')

The current price of COMP is $106.22.

In [19]:
# Set the tickers for both the bond and stock portion of the portfolio
# ids = {'aave'}

# Set timeframe to 1D 
timeframe = "1D"

# Format current date as ISO format
# Set both the start and end date at the date of your prior weekday 
# This will give you the closing price of the previous trading day

start_date = pd.Timestamp("2018-08-07", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2020-08-07", tz="America/New_York").isoformat()

In [20]:
# Set number of rows to 1000 to retrieve the maximum amount of rows
limit_rows = 1000

In [21]:
# Use CoinGecko API to pull data for aave
aave_prices = cg.get_coins_markets(
    vs_currency='usd',

)

aave_df = pd.DataFrame(aave_prices, columns =['id', 'current_price',  'market_cap'])
aave_df.set_index('id', inplace=True)

# Display both the first and last five rows of the DataFrame
aave_df.head()

             current_price    market_cap
id
bitcoin          37180.000  703722951867
ethereum          2580.210  308357369012
tether               1.001   79529285753
binancecoin        358.810   60038965385
usd-coin             1.004   52743788177

In [22]:
exchanges_list = cg.get_exchanges_list()

exchanges_list_df = pd.DataFrame(exchanges_list, columns= [ 'id','name','trust_score','trust_score_rank'])
exchanges_list_df.set_index('id',inplace=True)

exchanges_list_df

                             name  trust_score  trust_score_rank
id
binance                   Binance           10                 1
okex                          OKX           10                 2
gdax            Coinbase Exchange           10                 3
ftx_spot                      FTX           10                 4
crypto_com    Crypto.com Exchange           10                 5
...                           ...          ...               ...
bitvavo                   Bitvavo            6                96
quoine                     Liquid            6                97
sushiswap               Sushiswap            6                98
changelly           Changelly PRO            6                99
dodo_polygon       Dodo (Polygon)            5               100

[100 rows x 3 columns]

In [23]:
exchanges_list_df.head(50)

                               name  trust_score  trust_score_rank
id
binance                     Binance           10                 1
okex                            OKX           10                 2
gdax              Coinbase Exchange           10                 3
ftx_spot                        FTX           10                 4
crypto_com      Crypto.com Exchange           10                 5
kucoin                       KuCoin           10                 6
huobi                  Huobi Global           10                 7
gate                        Gate.io           10                 8
bitfinex                   Bitfinex           10                 9
kraken                       Kraken           10                10
binance_us               Binance US           10                11
bybit_spot             Bybit (spot)           10                12
gemini                       Gemini           10                13
bitkub                       Bitkub           10                14
bittrex                     Bittrex           10                15
xt                           XT.COM            9                16
mxc                     MEXC Global            9                17
bitmart                     BitMart            9                18
hoo                         Hoo.com            9                19
bitstamp                   Bitstamp            9                20
hotbit                       Hotbit            9                21
btcturk                 BtcTurk PRO            9                22
btse                           BTSE            9                23
bitget                       Bitget            9                24
blockchain_com       Blockchain.com            9                25
bitbank                     Bitbank            9                26
exmo                           EXMO            9                27
cex                          CEX.IO            9                28
bitso                         Bitso           10                29
bitrue                       Bitrue            8                30
digifinex                 Digifinex            8                31
bigone                       BigONE            8                32
lbank                         LBank            8                33
bithumb                     Bithumb            8                34
zb                               ZB            8                35
coinflex                   CoinFLEX            8                36
whitebit                   WhiteBIT            8                37
phemex                       Phemex            8                38
goku                     GokuMarket            8                39
ftx_us                       FTX.US            8                40
latoken                     LATOKEN            8                41
coinsbit                   Coinsbit            8                42
dextrade                  Dex-Trade            8                43
bitflyer                   bitFlyer            8                44
bitmax            AscendEX (BitMax)            8                45
decoin                       Decoin            8                46
poloniex                   Poloniex            8                47
coinex                       CoinEx            8                48
cryptology               Cryptology            8                49
kickex                       KickEX            8                50

In [245]:
# Get AAVE historical market cap directly from CoinGecko using CoinGeckoAPI()

aave_market_cap_cg = cg.get_coin_market_chart_by_id(id='aave', vs_currency='usd', days='2000')


# Get COMPOUND historical market cap directly from CoinGecko using CoinGeckoAPI()

comp_market_cap_cg = cg.get_coin_market_chart_by_id(id='compound-governance-token', vs_currency='usd', days='1000')


# Get Curve historical market cap directly from CoinGecko using CoinGeckoAPI()

curve_market_cap_cg = cg.get_coin_market_chart_by_id(id='curve-dao-token', vs_currency='usd', days='1000')


# Get Uniswap historical market cap directly from CoinGecko using CoinGeckoAPI()

uni_market_cap_cg = cg.get_coin_market_chart_by_id(id='uniswap', vs_currency='usd', days='1000')


# Get Maker Dao historical market cap directly from CoinGecko using CoinGeckoAPI()

maker_market_cap_cg = cg.get_coin_market_chart_by_id(id='maker', vs_currency='usd', days='1000')

#create a dataframe for each coin's market cap:
aave_market_cap_cg_df= pd.DataFrame(aave_market_cap_cg['market_caps'])
aave_market_cap_cg_df[0]= pd.to_datetime(aave_market_cap_cg_df[0], unit='ms')
aave_market_cap_cg_df.columns=['date', 'aave mcap']
aave_market_cap_cg_df.set_index('date',inplace=True)

comp_market_cap_cg_df= pd.DataFrame(comp_market_cap_cg['market_caps'])
comp_market_cap_cg_df[0]= pd.to_datetime(comp_market_cap_cg_df[0], unit='ms')
comp_market_cap_cg_df.columns=['date', 'comp mcap']
comp_market_cap_cg_df.set_index('date',inplace=True)

curve_market_cap_cg_df= pd.DataFrame(curve_market_cap_cg['market_caps'])
curve_market_cap_cg_df[0]= pd.to_datetime(curve_market_cap_cg_df[0], unit='ms')
curve_market_cap_cg_df.columns=['date', 'curve mcap']
curve_market_cap_cg_df.set_index('date',inplace=True)

uni_market_cap_cg_df= pd.DataFrame(uni_market_cap_cg['market_caps'])
uni_market_cap_cg_df[0]= pd.to_datetime(uni_market_cap_cg_df[0], unit='ms')
uni_market_cap_cg_df.columns=['date', 'uni mcap']
uni_market_cap_cg_df.set_index('date',inplace=True)

maker_market_cap_cg_df= pd.DataFrame(maker_market_cap_cg['market_caps'])
maker_market_cap_cg_df[0]= pd.to_datetime(maker_market_cap_cg_df[0], unit='ms')
maker_market_cap_cg_df.columns=['date', 'maker mcap']
maker_market_cap_cg_df.set_index('date',inplace=True)

#Combine the dataframes using pd.concat:

all_coins_mcap_df = pd.concat(
    [aave_market_cap_cg_df,
     comp_market_cap_cg_df, 
     curve_market_cap_cg_df, 
     uni_market_cap_cg_df,  
     maker_market_cap_cg_df], 
    axis=1
)

all_coins_mcap_df.drop_duplicates().groupby(['date']).sum()
all_coins_mcap_df = all_coins_mcap_df.mask(all_coins_mcap_df==0).ffill(downcast='infer').fillna(0)

all_coins_mcap_df.head()

            aave mcap  comp mcap  curve mcap  uni mcap    maker mcap
date
2019-05-30        0.0        0.0         0.0       0.0  7.577016e+08
2019-05-31        0.0        0.0         0.0       0.0  7.198506e+08
2019-06-01        0.0        0.0         0.0       0.0  7.397891e+08
2019-06-02        0.0        0.0         0.0       0.0  7.297946e+08
2019-06-03        0.0        0.0         0.0       0.0  7.319872e+08

AttributeError: 'CoinGeckoAPI' object has no attribute 'get_coin_tvl_by_id'

In [256]:
combined_mcap_tvl_df = pd.concat([
    all_coins_mcap_df, tvl_df], axis=1).groupby(['date']).sum()
combined_mcap_tvl_df = combined_mcap_tvl_df.mask(combined_mcap_tvl_df==0).ffill(downcast='infer').fillna(0)

combined_mcap_tvl_df.tail()

,aave mcap,comp mcap,curve mcap,uni mcap,maker mcap,AAVE TVL,COMP TVL,CURVE TVL,UNISWAP TVL,MAKER DAO TVL
date,,,,,,,,,,
2022-02-22 11:14:28,1.761972e+09,7.018940e+08,9.242833e+08,3.920301e+09,1.515760e+09,1.159063e+10,6.481427e+09,1.863420e+10,7.525129e+09,1.566187e+10
2022-02-22 11:35:14,1.761972e+09,7.018940e+08,9.242833e+08,3.954991e+09,1.515760e+09,1.159063e+10,6.481427e+09,1.863420e+10,7.525129e+09,1.566187e+10
2022-02-22 11:35:37,1.812171e+09,7.018940e+08,9.156892e+08,3.954991e+09,1.515760e+09,1.159063e+10,6.481427e+09,1.863420e+10,7.525129e+09,1.566187e+10
2022-02-22 11:36:04,1.812171e+09,7.253220e+08,9.156892e+08,3.954991e+09,1.515760e+09,1.159063e+10,6.481427e+09,1.863420e+10,7.525129e+09,1.566187e+10
2022-02-22 11:36:25,1.812171e+09,7.253220e+08,9.156892e+08,3.954991e+09,1.549238e+09,1.159063e+10,6.481427e+09,1.863420e+10,7.525129e+09,1.566187e+10